language: node_js
node_js:
  - "stable"
before_script:
  - npm install -g nyc coveralls codeclimate-test-reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build  
after_success:
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_script: 
  - nyc report --reporter=text-lcov | coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info