env: 
  global:
    - CC_TEST_REPORTER_ID: d951d71a92769d9b6b06038e570b774dac180024c3a9a411eb2b3e1f19179d9d
language: node_js
node_js:
  - "stable"
before_script:
  - psql -c 'create database myDiary;' -U postgres
  - npm install -g nyc coveralls codeclimate-test-reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
after_success:
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_script: 
  - nyc report --reporter=text-lcov | coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
  - PGPORT=5433      